#!/usr/bin/env python3

import cgi
import cgitb
import html  # <-- use this instead of cgi.escape()

# Enable detailed error messages in the browser
cgitb.enable()

# Parse form data
form = cgi.FieldStorage()
name = form.getvalue("name", "Guest")  # Default if not provided

# Output the required HTTP header
print("Content-Type: text/html; charset=utf-8")
print()  # Blank line between headers and body

# Output HTML
print(f"""\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Site — Greeting</title>
  <link rel="stylesheet" href="/assets/main.css">
</head>
<body>
  <header>
    <nav>
      <a href="/index.html">Index</a> |
      <a href="/home.html">Home</a>
    </nav>
  </header>
  <main>
    <section class="hero">
      <h1>Hello, {html.escape(name)}!</h1>
      <p>This page was generated by <code>file.py</code> (CGI).</p>
    </section>
  </main>
  <footer>
    <small>&copy; 2025</small>
  </footer>
</body>
</html>
""")



# test using:
# curl "localhost:8080/cgi-files/file.py?name=sunny"

# or this:
# curl -X POST -d "name=sunny" http://localhost:8080/cgi-bin/file.py