import cgi
import cgitb

cgitb.enable()

name = "test"

form = cgi.FieldStorage()
name = form.getvalue("name")

# print("<html>")
# print("<body>")
# print("<h1>Hello, {}!</h1>".format(name))
# print("</body>")
# print("</html>")

print("""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>Site — Greeting</title>
  <link rel="stylesheet" href="../assets/main.css">
</head>
<body>
  <header>
    <nav>
      <a href="/index.html">Index</a> |
      <a href="/home.html">Home</a>
    </nav>
  </header>
  <main>
    <section class="hero">
      <h1>Hello, {}!</h1>
      <p>This page was generated by <code>file.py</code> (CGI).</p>
    </section>
  </main>
  <footer>
    <small>&copy; 2025</small>
  </footer>
</body>
</html>
""".format(name))

# test using:
# curl "localhost:8080/cgi-files/file.py?name=sunny"

# or this:
# curl -X POST -d "name=sunny" http://localhost:8080/cgi-bin/file.py