import cgi
import cgitb

cgitb.enable()

name = "test"

form = cgi.FieldStorage()
name = form.getvalue("name")

print("<html>")
print("<head>")
print('  <meta charset="utf-8">')
print('  <meta name="viewport" content="width=device-width,initial-scale=1">')
print('  <title>Site — Greeting</title>')
print('  <link rel="stylesheet" href="./../assets/main.css">')
print("</head>")
print("<body>")
print("  <header>")
print("    <nav>")
print('      <a href="/index.html">Index</a> |')
print('      <a href="/home.html">Home</a>')
print("    </nav>")
print("  </header>")
print("  <main>")
print('    <section class="hero">')
print('      <h1>Hello, {}!</h1>'.format(name))
print('      <p>This page was generated by <code>file.py</code> (CGI).</p>')
print("    </section>")
print("  </main>")
print('  <footer>')
print('    <small>&copy; 2025</small>')
print("  </footer>")
print("</body>")
print("</html>")

# test using:
# curl "localhost:8080/cgi-files/file.py?name=sunny"

# or this:
# curl -X POST -d "name=sunny" http://localhost:8080/cgi-bin/file.py