#!/usr/bin/env php-cgi
<?php
function h($s) {
    return htmlspecialchars($s, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

// Helper: robustly obtain a request parameter (fallback to raw QUERY_STRING / POST body)
function get_param($key) {
    // 1) normal superglobals
    if (isset($_REQUEST[$key]) && $_REQUEST[$key] !== '') {
        return $_REQUEST[$key];
    }

    // 2) parse QUERY_STRING env
    $qs = getenv('QUERY_STRING');
    if ($qs === false || $qs === null) {
        $qs = isset($_SERVER['QUERY_STRING']) ? $_SERVER['QUERY_STRING'] : '';
    }
    if ($qs) {
        parse_str($qs, $out);
        if (isset($out[$key]) && $out[$key] !== '') {
            return $out[$key];
        }
    }

    // 3) if POST, read raw body and parse
    $method = getenv('REQUEST_METHOD');
    if ($method === false || $method === null) {
        $method = isset($_SERVER['REQUEST_METHOD']) ? $_SERVER['REQUEST_METHOD'] : '';
    }
    if (strtoupper($method) === 'POST') {
        $raw = file_get_contents('php://input');
        if ($raw) {
            parse_str($raw, $post);
            if (isset($post[$key]) && $post[$key] !== '') {
                return $post[$key];
            }
        }
    }

    return null;
}

$name = get_param('name');
if ($name === null || $name === '') {
    $name = 'Guest';
}
$safe_name = h($name);

echo "Content-Type: text/html\r\n\r\n";

echo '<!DOCTYPE html>' . "\n";
echo '<html lang="en">' . "\n";
echo '<head>' . "\n";
echo '    <meta charset="UTF-8">' . "\n";
echo '    <meta name="viewport" content="width=device-width, initial-scale=1.0">' . "\n";
echo '    <title>PHP CGI Example - Webserv</title>' . "\n";
echo '    <link rel="stylesheet" href="./../assets/main.css">' . "\n";
echo '</head>' . "\n";
echo '<body>' . "\n";
echo '    <div class="container">' . "\n";
echo '        <header class="header">' . "\n";
echo '            <h1>Webserv Project</h1>' . "\n";
echo '            <p class="subtitle">PHP CGI Example</p>' . "\n";
echo '        </header>' . "\n";
echo '' . "\n";
echo '        <main class="content">' . "\n";
echo '            <section class="project-info">' . "\n";
echo '                <h2>This is a PHP CGI example</h2>' . "\n";
echo '                <p>Hello, ' . $safe_name . '! This content was generated by <code>index.php</code> (PHP CGI).</p>' . "\n";
echo '' . "\n";
echo '                <div class="info-grid">' . "\n";
echo '                    <div class="info-card">' . "\n";
echo '                        <h3>CGI</h3>' . "\n";
echo '                        <p>Common Gateway Interface scripts run on the server to generate dynamic content.</p>' . "\n";
echo '                    </div>' . "\n";
echo '                    <div class="info-card">' . "\n";
echo '                        <h3>Usage</h3>' . "\n";
echo '                        <p>Place your scripts in <code>www/cgi-bin/</code> and ensure they are executable. Use query strings or POST to pass data.</p>' . "\n";
echo '                    </div>' . "\n";
echo '                    <div class="info-card">' . "\n";
echo '                        <h3>Security</h3>' . "\n";
echo '                        <p>Sanitize inputs and avoid exposing sensitive data from CGI scripts.</p>' . "\n";
echo '                    </div>' . "\n";
echo '                </div>' . "\n";
echo '' . "\n";
echo '                <p style="margin-top:1.5rem;">' . "\n";
echo '                    <a href="../index.html" class="back-link">← Back to Index</a>' . "\n";
echo '                </p>' . "\n";
echo '            </section>' . "\n";
echo '        </main>' . "\n";
echo '' . "\n";
echo '        <footer class="footer">' . "\n";
echo '            <p>&copy; 2025 1337 - Webserv Project</p>' . "\n";
echo '        </footer>' . "\n";
echo '    </div>' . "\n";
echo '</body>' . "\n";
echo '</html>' . "\n";

?>
