#!/usr/bin/env php-cgi
<?php
// Ensure PHP CGI outputs header and HTML matching site layout
function h($s) {
    return htmlspecialchars($s, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8');
}

$name = isset($_REQUEST['name']) && $_REQUEST['name'] !== '' ? $_REQUEST['name'] : 'Guest';
$safe_name = h($name);

// Output required CGI header
echo "Content-Type: text/html\r\n\r\n";

echo '<!DOCTYPE html>' . "\n";
echo '<html lang="en">' . "\n";
echo '<head>' . "\n";
echo '    <meta charset="UTF-8">' . "\n";
echo '    <meta name="viewport" content="width=device-width, initial-scale=1.0">' . "\n";
echo '    <title>PHP CGI Example - Webserv</title>' . "\n";
echo '    <link rel="stylesheet" href="../assets/main.css">' . "\n";
echo '</head>' . "\n";
echo '<body>' . "\n";
echo '    <div class="container">' . "\n";
echo '        <header class="header">' . "\n";
echo '            <h1>Webserv Project</h1>' . "\n";
echo '            <p class="subtitle">PHP CGI Example</p>' . "\n";
echo '        </header>' . "\n";
echo '' . "\n";
echo '        <main class="content">' . "\n";
echo '            <section class="project-info">' . "\n";
echo '                <h2>This is a PHP CGI example</h2>' . "\n";
echo '                <p>Hello, ' . $safe_name . '! This content was generated by <code>index.php</code> (PHP CGI).</p>' . "\n";
echo '' . "\n";
echo '                <div class="info-grid">' . "\n";
echo '                    <div class="info-card">' . "\n";
echo '                        <h3>CGI</h3>' . "\n";
echo '                        <p>Common Gateway Interface scripts run on the server to generate dynamic content.</p>' . "\n";
echo '                    </div>' . "\n";
echo '                    <div class="info-card">' . "\n";
echo '                        <h3>Usage</h3>' . "\n";
echo '                        <p>Place your scripts in <code>www/cgi-bin/</code> and ensure they are executable. Use query strings or POST to pass data.</p>' . "\n";
echo '                    </div>' . "\n";
echo '                    <div class="info-card">' . "\n";
echo '                        <h3>Security</h3>' . "\n";
echo '                        <p>Sanitize inputs and avoid exposing sensitive data from CGI scripts.</p>' . "\n";
echo '                    </div>' . "\n";
echo '                </div>' . "\n";
echo '' . "\n";
echo '                <p style="margin-top:1.5rem;">' . "\n";
echo '                    <a href="../index.html" class="back-link">← Back to Index</a>' . "\n";
echo '                </p>' . "\n";
echo '            </section>' . "\n";
echo '        </main>' . "\n";
echo '' . "\n";
echo '        <footer class="footer">' . "\n";
echo '            <p>&copy; 2025 1337 - Webserv Project</p>' . "\n";
echo '        </footer>' . "\n";
echo '    </div>' . "\n";
echo '</body>' . "\n";
echo '</html>' . "\n";

?>
