#!/usr/bin/env python3
import cgi
import cgitb

cgitb.enable()

name = "test"

form = cgi.FieldStorage()
name = form.getvalue("name")

print('<html')
print('<head>')
print('    <meta charset="UTF-8">')
print('    <meta name="viewport" content="width=device-width, initial-scale=1.0">')
print('    <title>Python CGI Example - Webserv</title>')
print('    <link rel="stylesheet" href="../assets/main.css">')
print('</head>')
print('<body>')
print('    <div class="container">')
print('        <header class="header">')
print('            <h1>Webserv Project</h1>')
print('            <p class="subtitle">Python CGI Example</p>')
print('        </header>')
print('')
print('        <main class="content">')
print('            <section class="project-info">')
print('                <h2>This is a Python CGI example</h2>')
print('                <p>Hello, {}! This content was generated by <code>index.py</code> (Python CGI).</p>'.format(name))
print('')
print('                <div class="info-grid">')
print('                    <div class="info-card">')
print('                        <h3>CGI</h3>')
print('                        <p>Common Gateway Interface scripts run on the server to generate dynamic content.</p>')
print('                    </div>')
print('                    <div class="info-card">')
print('                        <h3>Usage</h3>')
print('                        <p>Place your scripts in <code>www/cgi-bin/</code> and ensure they are executable. Use query strings or POST to pass data.</p>')
print('                    </div>')
print('                    <div class="info-card">')
print('                        <h3>Security</h3>')
print('                        <p>Sanitize inputs and avoid exposing sensitive data from CGI scripts.</p>')
print('                    </div>')
print('                </div>')
print('')
print('                <p style="margin-top:1.5rem;">')
print('                    <a href="../index.html" class="back-link">← Back to Index</a>')
print('                </p>')
print('            </section>')
print('        </main>')
print('')
print('        <footer class="footer">')
print('            <p>&copy; 2025 1337 - Webserv Project</p>')
print('        </footer>')
print('    </div>')
print('</body>')
print('</html>')

# test using:
# curl "localhost:8080/cgi-files/file.py?name=sunny"

# or this:
# curl -X POST -d "name=sunny" http://localhost:8080/cgi-bin/file.py
